spring:
  security:
      name: user
      password: 1234
  application:
    name: Maintenance_App
  datasource:
    url: jdbc:postgresql://localhost:5432/residency_management
    username: postgres
    password: Pravin@69
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    
jwt:
  secret: 4y+3rvem1icxOqAP8+THNo3fI760btfh8A0lrW6+P7Y=
  expiration: 86400000


server:
  port: 8081

maintenance:
  monthly-amount: 500.00